exclude

diff --git a/.github/workflows/15-matrices.yaml b/.github/workflows/15-matrices.yaml
--- a/.github/workflows/15-matrices.yaml
+++ b/.github/workflows/15-matrices.yaml
@@ -4,39 +4,39 @@ on:
     workflow_dispatch: 
 
 jobs:
-    backwards-compatibility:
-        name: ${{matrix.os}}-${{matrix.node-version}}-${{matrix.tag}}
-        runs-on: ${{matrix.os}}
-        strategy:
-            fail-fast: true
-            matrix:
-                node-version: [18.x, 20.x, 21.x]
-                os: [ubuntu-latest, windows-latest]
-                include:
-                    - os: ubuntu-latest
-                      tag: experimental
+    # backwards-compatibility:
+    #     name: ${{matrix.os}}-${{matrix.node-version}}-${{matrix.tag}}
+    #     runs-on: ${{matrix.os}}
+    #     strategy:
+    #         fail-fast: true
+    #         matrix:
+    #             node-version: [18.x, 20.x, 21.x]
+    #             os: [ubuntu-latest, windows-latest]
+    #             include:
+    #                 - os: ubuntu-latest
+    #                   tag: experimental
 
-                    - node-version: 21.x
-                      tag: experimental
+    #                 - node-version: 21.x
+    #                   tag: experimental
 
-                    - os: ubuntu-latest
-                      node-version: 16.x
-        steps:
-            - name: Setup Node
-              uses: actions/setup-node@v3
-              with:
-                node-version: ${{matrix.node-version}}
+    #                 - os: ubuntu-latest
+    #                   node-version: 16.x
+    #     steps:
+    #         - name: Setup Node
+    #           uses: actions/setup-node@v3
+    #           with:
+    #             node-version: ${{matrix.node-version}}
 
-            - name: Perform some tests
-              run: |
-                sleep 10 && echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
+    #         - name: Perform some tests
+    #           run: |
+    #             sleep 10 && echo "Running tests on OS ${{matrix.os}} and NodeJS ${{matrix.node-version}}"
 
-            - name: Upload test results
-              run: echo "Uploading test results"
+    #         - name: Upload test results
+    #           run: echo "Uploading test results"
 
-            - name: Fail if experimental
-              if: ${{matrix.tag == 'experimental'}}
-              run: exit 1
+    #         - name: Fail if experimental
+    #           if: ${{matrix.tag == 'experimental'}}
+    #           run: exit 1
     
     include-example:
         runs-on: ubuntu-latest
@@ -54,6 +54,8 @@ jobs:
               - color: red
                 shape: triangle
               - opacity: 50
+            exclude:
+              - opacity: 75
             
         steps:
           - name: Dummy step
